version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started 
      - echo Building the Docker image now...
      - echo "$CODEBUILD_WEBHOOK_TRIGGER" | cut -d'/' -f 2
      - t=$(echo "$CODEBUILD_WEBHOOK_TRIGGER" | cut -d'/' -f 2)
      - docker build -t abcdefs:$t-$CODEBUILD_BUILD_NUMBER .
